name: Staging End-to-end tests
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  cypress-staging:
    runs-on: ubuntu-22.04
    environment: STAGING
    container:
      image: cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4   
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        env:
          CYPRESS_USERNAME: ${{env.USERNAME}}
          CYPRESS_PASSWORD: ${{secrets.PASSWORD}}
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - name: Generate Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress-execution-report
            path: cypress/reports/html
            if-no-files-found: ignore